import os
os.system('clear')
print('OPERATOR AND --- It will only True be if all values are True')
print('True and True')
print(True and True)
print('\nTrue and False')
print(True and False)
print('\nFalse and True')
print(False and True)
print('\nFalse and False')
print(False and False)
print('-------------------------------------------\n')
print('OPERATOR OR --- If a value is True the boolean value will be True')
print('False or False')
print(False or False)
print('\nFalse or True')
print(False or True)
print('\nTrue or False')
print(True or False)
print('-------------------------------------------\n')
print('OPERATOR NOT --- Change the value')
print('not True')
print(not True)
print('\nnot False')
print(not False)
print('\nnot not not True')
print(not not not True)